version: '3.5'
services:
  web:
    ports:
      - "11451:43213"
    environment:
      DHPROXY_UPSTREAM: <PROXY_SERVER_URL>
      DHPROXY_ROOT: <WEB_ROOT>
    image: ghcr.io/klrohias/docker-hub-proxy:latest
